server:
  port: 9000
  netty:
    connection-timeout: 2s
    idle-timeout: 15s
  shutdown: graceful

spring:
  application:
    name: edge-service
  lifecycle:
    timeout-per-shutdown-phase: 15s

  cloud:
    gateway:
      routes:
        - id: catalog-service
          # If the env var isn't defined the first part after : will be used so for this it would be = http://localhost:9001
          uri: ${CATALOG_SERVICE_URL:http://localhost:9001}/books
          predicates:
            - Path=/books/**
        - id: order-route
          # If the env var isn't defined the first part after : will be used so for this it would be = http://localhost:9002
          uri: ${ORDER_SERVICE_URL:http://localhost:9002}/orders
          predicates:
            - Path=/orders/**