apiVersion: v1
kind: Service # This is to expose the edge-service application through kubernetes DNS service discover
metadata:
  name: edge-service # Name of the service - must be a valid DNS name
  labels:
    app: edge-service
spec:
  type: ClusterIP
  selector:
    app: edge-service
  ports:
    - protocol: TCP
      port: 80 # Port exposed by the Service
      targetPort: 9000 # Port exposed by the pods targeted by the service